name: "build-push-postgres-16_2_vanilla_w_pg_cron"
on:
  push:
    branches: [main]

# in case of back-to-back deploy, we cancel older deploy
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

env:
  DOCKER_REPOSITORY: postgres_w_pg_cron
  IMAGE_TAG: latest

jobs:
  build:
    runs-on: ${{ matrix.profile }}
    strategy:
      matrix:
        include:
          - profile: namespace-profile-amd64
            platform: amd64
          - profile: namespace-profile-arm64
            platform: arm64
    outputs:
      image_source: ${{steps.build_push_image.outputs.image}}
    steps:
      - uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: scripts/custom_docker_images
          file: scripts/custom_docker_images/Dockerfile
          tags: "${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_REPOSITORY }}:${{ env. IMAGE_TAG }}_${{ matrix.platform }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max
